language: ruby
cache: bundler
sudo: false
bundler_args: --without development --jobs 2

services:
  - redis-server

addons:
  postgresql: "9.4"

env:
  global:
    - DB=postgresql
    - KINDLEGEN_PATH=/tmp/kindlegen/kindlegen
    - ES_VERSION=2.3.3

before_install:
  - mkdir /tmp/elasticsearch
  - wget -O - https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - /tmp/elasticsearch/bin/elasticsearch --daemonize --path.data /tmp
  - mkdir /tmp/kindlegen
  - wget -O - http://kindlegen.s3.amazonaws.com/kindlegen_linux_2.6_i386_v2_9.tar.gz | tar xz --directory=/tmp/kindlegen

before_script:
  - psql -c 'create database feedbin_test;' -U postgres
  - bundle exec rake db:setup
  - bundle exec rake db:test:prepare
  - curl http://127.0.0.1:9200/
