language: ruby
cache: bundler
sudo: false
services:
  - redis-server
addons:
  postgresql: "9.4"
env:
  - DB=postgresql
bundler_args: --without production development
before_script:
  - psql -c 'create database feedbin_test;' -U postgres
before_script:
  - export POSTGRES_USERNAME=postgres
  - export AWS_ACCESS_KEY_ID=foo
  - export AWS_SECRET_ACCESS_KEY=bar
  - bundle exec rake db:setup
  - bundle exec rake db:test:prepare
