language: ruby
cache: bundler
sudo: false
bundler_args: --without development --jobs 2

services:
  - redis-server

addons:
  postgresql: "9.4"

env:
  global:
    - APPLE_PUSH_WEBSITE_ID=com.example
    - AWS_ACCESS_KEY_ID=foo
    - AWS_SECRET_ACCESS_KEY=bar
    - DB=postgresql
    - POSTGRES_USERNAME=postgres
    - PUSH_URL=http://example.com
  matrix:
    - ES_VERSION=2.3.3

before_install:
  - mkdir /tmp/elasticsearch
  - wget -O - https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.tar.gz | tar xz --directory=/tmp/elasticsearch --strip-components=1
  - /tmp/elasticsearch/bin/elasticsearch --daemonize --path.data /tmp

before_script:
  - psql -c 'create database feedbin_test;' -U postgres
  - bundle exec rake db:setup
  - bundle exec rake db:test:prepare
  - curl http://127.0.0.1:9200/
