language: ruby
cache: bundler
sudo: true
bundler_args: --without production development
services:
  - redis-server
addons:
  postgresql: "9.4"
env:
  - DB=postgresql
before_install:
  - curl -LO https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-2.3.4.deb && sudo dpkg -i --force-confnew elasticsearch-2.3.4.deb && sudo service elasticsearch restart
before_script:
  - export POSTGRES_USERNAME=postgres
  - export AWS_ACCESS_KEY_ID=foo
  - export AWS_SECRET_ACCESS_KEY=bar
  - psql -c 'create database feedbin_test;' -U postgres
  - bundle exec rake db:setup
  - bundle exec rake db:test:prepare
